environment:
  matrix:
    - GENERATOR: Visual Studio 14 2015 Win64

branches:
  except:
    - /^(wip\/)?(travis|osx|ipp)(\-.+)?$/
    - /^master$/

before_build:
  - ps: |
      git submodule -q update --init --recursive
      cd test
      mkdir build
      cd build
      cmake -G "$env:GENERATOR" ..

build_script:
  - ps: |
      cmake --build . --config Debug

test_script:
  - ps: |
      ctest --output-on-failure --interactive-debug-mode 0 -C Debug -V
